### ISSUE TITLE
Github action: check addresses against running networks

### ISSUE THREAD

**Issue by edd** [vegaprotocol/smart-contracts-sdk#12]
If run nightly, this might be a useful heads up if a governance action changed the contract that is being used. For example if on Fairground, a governance action updated the bridge address, a [nightly/hourly/other] action run could raise a PR to this repo to update the address

# Tasks
- [ ] Add an action that can be run periodically
- [ ] That has the API addresses for all relevant networks, and the Network Parameter that configures each contract
- [ ] And will check that the address in this repo matches the network parameter
- [ ] And if it doesn't, can raise an issue or PR to change it
